### PR TITLE
Introduce a 'foldMap' variant for cats.Semigroup

### LINKED ISSUE #119: Introduce a foldMap variant for Semigroup
It would need either to take an initial value or return an optional one (see [this comment](https://github.com/travisbrown/iteratee/pull/104/files#r75601308)).

### PR DESCRIPTION
**Pull request by ilya-murzinov**
Resolves #119

### CODE REVIEW

**Comment by travisbrown** [comment]
Thanks @ilya-murzinov! I'd rather not introduce overloading, though (in part because of the hit to type inference that you see in the benchmark line).

I'd be tempted to suggest going the other route (`Option` in return type) and calling it `foldMapOption`, since this follows the pattern of `reduceRightOption`, `maximumOption`, etc. in Cats's `Foldable`. What do you think?

**Comment by ilya-murzinov** [comment]
@travisbrown ok, sure, let me try to implement this.

**Comment by ilya-murzinov** [comment]
@travisbrown does this look more or less what you were thinking of?
BTW, can't figure out why tests are failing.
The other strange thing is that CI build is passing. Probably should check config.

**Comment by travisbrown** [comment]
@ilya-murzinov Thanks for catching the CI issue—I think #147 should fix it. Fortunately it looks like we just need to bump up the timeouts for the `Future` tests.

About the `foldMapOption` failures—I think the following is a reasonable (simpler) implementation:

```scala
  final def foldMapOption[F[_], E, A](f: E => A)(implicit F: Applicative[F], S: Semigroup[A]): Step[F, E, Option[A]] =
    foldMap[F, E, Option[A]](e => Some(f(e)))(F, cats.kernel.instances.option.catsKernelStdMonoidForOption[A])
```

This passes for me locally. It looks like the issue with yours is that a single `None` causes the result to be `None`, instead of the `Monoid` behavior for `None` being used.

**Comment by ilya-murzinov** [comment]
@travisbrown yep, I had a feeling that this can be done by reusing ```foldMap``` but could not figure out the way. Thanks!

**Comment by travisbrown** [comment]
Thanks @ilya-murzinov! Will merge when green.

**Comment by ilya-murzinov** [comment]
I rebased it on ```master``` so should be OK now

**Pull request merged**
