### PR TITLE
Add fs2 module

### LINKED ISSUE #166: Add fs2 module
I'd like to add a module with support for fs2's `Task` that's similar to what we have for Scalaz, as well as some converters to and from fs2's types.

### PR DESCRIPTION
**Pull request by ilya-murzinov**
Resolves #166

### CODE REVIEW

**Comment by travisbrown** [comment]
Nice, thanks! I was wanting to get this into the next release (which will be immediately after Cats 0.9.0), but didn't know if I'd have time.

**Comment by ilya-murzinov** [comment]
Hmmm, test is failing with Scala 2.12 and jdk8..
Let me try to figure out why.

**Comment by ilya-murzinov** [comment]
Ok, got it.

**Comment by ilya-murzinov** [comment]
I also added tests for monix

**Comment by travisbrown** [comment]
👍, looks great, thanks!

**Pull request merged**
